jobs:
- name: update-jira
  plan:
  - get: jira-resource
  - put: jira
    params:
      summary: Example jira ticket
      description: Example text
      issue_type: Change
      environment: PROD
      duedate: $NOW+1H
      custom_fields:
        agcc_impact:
          id: 10201
          value: "none"

resources:
  - name: jira-resource
    type: git
    source:
      uri: git@github.com:danrspencer/jira-resource.git
      branch: node-version
      private_key: {{private-repo-key}}

  - name: jira
    type: jira
    source:
      url: {{jira-url}}
      username: {{jira-username}}
      password: {{jira-password}}
      project: {{jira-project}}

resource_types:
- name: jira
  type: docker-image
  source:
    repository: danrspencer/jira-resource
    tag: 0.1.0
