jobs:
- name: test
  plan:
  - get: jira-resource
    trigger: true
  - task: run-tests
    config:
      platform: linux
      image_resource:
        source:
          repository: mhart/alpine-node
        type: docker-image
      inputs:
      - name: jira-resource
      run:
        path: (cd jira-resource && npm install && npm test)

- name: build
  plan:
  - get: jira-resource
    trigger: true
    passed: [ test ]
  - put: docker-image-jira-resource
    params:
      build: jira-resource

resources:
  - name: jira-resource
    type: git
    source:
      uri: git@github.com:danrspencer/jira-resource.git
      branch: node-version
      private_key: {{private-repo-key}}

  - name: docker-image-jira-resource
    type: docker-image
    source:
      repository: danrspencer/jira-resource
      username: danrspencer
      password: boccie.tapestry.conjoint.communal.binary
      email: danrspen@gmail.com
