jobs:
- name: build
  public: true
  plan:
  - get: jira-resource
    trigger: true
  - put: docker-image-jira-resource
    params:
      build: jira-resource

resources:
  - name: jira-resource
    type: git
    source:
      uri: git@github.com:danrspencer/jira-resource.git
      branch: master
      private_key: {{private-repo-key}}

  - name: docker-image-jira-resource
    type: docker-image
    source:
      repository: danrspencer/jira-resource
      username: danrspencer
      password: boccie.tapestry.conjoint.communal.binary
      email: danrspen@gmail.com
